# Generated by Django 4.0.3 on 2022-05-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_address_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address_depart',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
