# Generated by Django 4.0.3 on 2022-05-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
