# Generated by Django 4.0.3 on 2022-05-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='letter',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='grade',
            name='level',
            field=models.CharField(max_length=10),
        ),
    ]
