# Generated by Django 4.0.3 on 2022-06-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_alter_grade_letter_alter_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='sublevel',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
