# Generated by Django 4.0.3 on 2022-06-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_grade_sublevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='sublevel',
            field=models.CharField(choices=[('PREBÁSICA', 'PREBÁSICA'), ('BÁSICA', 'BÁSICA')], max_length=10, null=True),
        ),
    ]
